### ISSUE TITLE
HTTP + socks5 卡顿

### ISSUE THREAD

**Issue by evi1ox** [liuaifu/asio5#2]
经常出现卡顿情况......
00:54:10.359181 <debug> [27] 3.3.3.2:51069 connected
00:54:21.171294 <debug> [28] 3.3.3.2:51075 connected
00:54:21.171294 <debug> [29] 3.3.3.2:51076 connected
00:54:21.171294 <debug> [27] open baidu.com
00:54:21.171294 <debug> [28] open baidu.com
00:54:21.171294 <debug> [29] open baidu.com

正常的情况
00:53:20.828601 <debug> [23] 3.3.3.2:50950 connected
00:53:20.843409 <debug> [23] open baidu.com
00:53:21.063101 <debug> [23] End of file
00:53:21.063101 <debug> [23] 由本地系统中止网络连接。
00:53:21.125551 <debug> [24] 3.3.3.2:50952 connected
00:53:21.125551 <debug> [24] open baidu.com
00:53:21.406852 <debug> [24] End of file

很 LOW的解决办法:
     在服务端控制台任意按键就可以恢复连接...

**Comment by liuaifu** [comment]
@evi1ox 是Windows server是吧？我在桌面版系统使用没遇到，有空了做成服务。

**Comment by evi1ox** [comment]
nice!

**Comment by liuaifu** [comment]
@evi1ox 终端卡顿的问题在其它时候偶有遇到，老外说是由于“快速编辑模式”引起的：
https://superuser.com/questions/312132/command-prompt-hangs-until-keypress
关闭试试。
